### ISSUE TITLE
Tijdsannotatie

### ISSUE THREAD

**Issue by pietercolpaert** [Informatievlaanderen/generieke-hypermedia-api#13]
Als er meerdere observaties of versies in 1 HTTP-response worden weergegeven, moet er onderscheid gemaakt kunnen worden.

Voorstel:

Gebruik van [PROV-O ontologie](https://www.w3.org/TR/prov-o/). 

Voorbeeld:
```trig
<#observation1> {
   # mijn data binnen observation1
}
<#observation1> prov:generatedAtTime "2018-06-01T12:00Z"^^xsd:dateTime .
```

Compliant aan W3C RSP aanpak: https://www.w3.org/community/rsp/

**Comment by rubensworks** [comment]
> of versies

Tijd is niet altijd voldoende om alle mogelijke versies voor te stellen.
Bijvoorbeeld, Git commit hashes identificeren versies aan binnen repositories.
Hiervoor zou bijvoorbeeld [`ver:relatedVersion`](http://semweb.datasciencelab.be/ns/version/#relatedVersion) gebruikt worden.

**Comment by CumpsD** [comment]
Kan je dit in layman termen eens uitleggen aub? Voor iemand die niet snapt wat PROV-O, ontologie of RDF is :) 

Gaat deze discussie over 1 reply die voor een object meerdere versies teruggeeft, en waar we nu kijken of tijd een uniek gegeven is om die uit elkaar te kunnen houden? 

Als dat zo is, dan volg ik enerzijds @rubensworks, tijd is niet uniek voor versies. Anderzijds, is dat niet aan de applicatie om te beslissen hoe versionering van objecten gedaan wordt? Lijkt me niet iets dat een generieke bouwblok moet doen, die moet versies waarschijnlijk eerder als een string zien die uniek is?

**Comment by pietercolpaert** [comment]
Het ging mij vooral over documenteren van time series. Na discussie met @rubensworks merk ik dat je issue #10 en #1 zou kunnen samensmijten om dit te doen. Ik zie het dan ook momenteel als een afgeleide specificatie op basis van dit document en mag wat mij betreft gesloten worden!

**Comment by jensscheerlinck** [comment]
Het aspect van data te metadateren met tijdsannotaties zit momenteel vervat in de specificatie voor de [bouwblok rond versionering van data](https://github.com/Informatievlaanderen/generieke-hypermedia-api/blob/master/versionering.md).
