### ISSUE TITLE
Repo locatie

### ISSUE THREAD

**Issue by CumpsD** [Informatievlaanderen/generieke-hypermedia-api#16]
@pietercolpaert ik weet dat jij waarschijnlijk het meeste voorbereidende werk gedaan hebt, maar misschien moet deze repo moven onder een organisatie ipv persoonlijk? Perceptie enzo, als ik nu al zie hoe gevoelig GitHub op zich soms al ligt in deze discussies, moeten we alle mogelijke bronnen van argumenten misschien wegnemen?

**Comment by pietercolpaert** [comment]
Goed punt. Toen ik dit zelf voorstelde aan @rafbuyle en @jensscheerlinck stelden ze zelf voor liever een ad-hoc repository te gebruiken. Ik kan deze repo zelf moven naar bvb https://github.com/smartflanders -- Andereorganisaties heb ik geen toegang toe. Wat stel je voor?

**Comment by CumpsD** [comment]
Eerlijk gezegd geen idee, misschien best voor @rafbuyle om te beslissen, of Ziggy, aangezien ik denk dat dit initiatief onder hen valt. Weet niet in welke mate het eventueel onder die van agentschap Informatie Vlaanderen valt, of dat ok is bijvoorbeeld

**Comment by koenedaele** [comment]
Ik zou dit ook liever onder Informatie Vlaanderen zien staan. Of een aparte OSLO2 organisatie als die bestaat. Nu lijkt het een persoonlijk initiatief van @pietercolpaert  te zijn.

**Comment by pietercolpaert** [comment]
Ben in contact met iemand die me creation access zou moeten geven op Informatie Vlaanderen repo’s. Komt in orde!

**Comment by pietercolpaert** [comment]
De repository staat nu officieel onder Informatie Vlaanderen!
